params:
  objective: reg:squarederror
  eval_metric: mae
  eta: 0.05
  subsample: 0.8
  colsample_bytree: 0.8
  alpha: 0.01
  lambda: 0.01
  seed: 42
  n_jobs: -1
path: resources/models/
name: xgboost
results: 5fold-mae-xgboost
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 250