defaults:
  - _self_
  - data: dataset
  - models: lightgbm
  - features: featurize
  - experiment: wandb
  - hydra: custom
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled